### ISSUE TITLE
Pass context to Dialogflow with Query Input

### ISSUE THREAD

**Issue by finnborchers** [Deimos-Applications/dialog_flowtter#11]
I there a way to pass a context to Dialogflow using the QueryInput?
There is a EventInput field to pass an event in. But is it also possible to predefine the conversation context from the flutter app when sending a query?

And if not, how would it be possible to continue a Dialogflow conversation after a certain period of time (The session of a conversation only lasts for about 20 minutes)?

I am thankful for any answer.

**Comment by ElZombieIsra** [comment]
Hi! Of course you can do that.

When calling `detectIntent` you can pass a `QueryParameters` object. There you can add a list of contexts to send to the bot

```dart
final params = QueryParameters(
    contexts: [
        Context(name: "MY_NAME"),
        Context(lifespan: MY_LIFESPAN),
    ],
);
```

And then add it to the `detectIntent` function

```dart
final response = await dialogFlowtter.detectIntent(
  queryInput: queryInput,
  queryParams: params,
);
```

I recommend you checking out the `QueryParams` and `Context` classes to see everything that you can add to them.

Let me know if this solves your question.

**Comment by finnborchers** [comment]
Thank you so much for your answer. Because it is so well documented I instantly found my mistake.
This is how I set the Context:

```
Context(
            name:
              "projects/{project_id=*}/locations/{location_id=*}/agent/environments/{environment_id=*}/users/{user_id=*}/sessions/{session_id=*}/contexts/start",
            lifespanCount: 10000,)
```

**Comment by finnborchers** [comment]
Great plugin!! Thanks!

**Comment by ElZombieIsra** [comment]
I'm glad I could help!
