### ISSUE TITLE
Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>?' in type cast

### ISSUE THREAD

**Issue by 61130500217** [Deimos-Applications/dialog_flowtter#12]
It happens with this code initialization even it is out of the Future<>() or make it look like the the document.
![image](https://user-images.githubusercontent.com/47667203/133926604-b5474053-923b-4bdf-944e-e0664ee4914e.png)

There is no any error with one response text. But always with many text responses text and it does not give any response but the error 

![image](https://user-images.githubusercontent.com/47667203/133926695-bb16f104-3f45-40ac-95ba-338edeabf5c7.png)

Most of my intent contain more than 1 text responses and pictures.

I use  version 0.3.1 

I'm struggling with it for many days ...

**Comment by faheem4797** [comment]
hi @61130500217! Did you find any solution to this?

**Comment by ElZombieIsra** [comment]
Hey guys. Sorry for not being active but I've been pretty busy. 

If you can look into why this is happening that would be pretty helpful. 

It sounds like a type that DialogFlow is returning in it's JSON response it's different than the one I have mapped in the models. You can try and use the VSCode debugger on the line where that its happening. 
Be sure that, on the bottom bar, the option "Debug my code + packages" is active.

**Comment by Makdan1** [comment]
<img width="522" alt="Screenshot 2021-11-13 at 10 52 22 pm" src="https://user-images.githubusercontent.com/36858866/141660032-14976fe3-358b-4d02-bfff-3516209cb0d6.png">
This is where the is coming from

**Comment by bashiryousufy** [comment]
I have the same issue, where dialogflow is replying with carousel or suggestion chip the library just shows this error. It doesn't show the message type or its content.

Please kindly help us on this issue, i have been stuck here for sometime now.

**Comment by bashiryousufy** [comment]
@Makdan1 Did you manage to find any solution for above problem?

**Comment by ElZombieIsra** [comment]
Hey, guys. I'm not being able to recreate the issue here. I'm setting multiple text responses in the Dialogflow intent but it seems to be working fine. 

This is how I'm doing it 
![Captura de pantalla 2022-01-06 a las 12 21 22 p m](https://user-images.githubusercontent.com/17725111/148431726-4e25cc05-0113-41ba-a800-02092ae146d4.png)

Can one of you write a small guide on how are you setting the responses for this to happen? 

Thanks

**Comment by bashiryousufy** [comment]
Text Responses are actually ok but we have issue with rich message such suggestion chip or carousel 

![image](https://user-images.githubusercontent.com/57277671/148581735-5d9eec34-5260-4e99-b946-f5fcc6b6611e.png)

**Comment by Makdan1** [comment]
> @Makdan1 Did you manage to find any solution for above problem?

I had to use another package.

**Comment by bashiryousufy** [comment]
> > @Makdan1 Did you manage to find any solution for above problem?
> 
> I had to use another package.

Yeah, I'm also using another package it doesn't have models for each response but they at least provide the json response from dialog flow so you work from there.

**Comment by reconftw010101** [comment]
@bashiryousufy  @Makdan1   Can you guys suggest another package with null aware working with latest update of flutter? I have problem wtih welcome intent as well as suggestion chips from google assistance.

**Comment by JLT-Labs** [comment]
> > > @Makdan1 Did you manage to find any solution for above problem?
> > 
> > 
> > I had to use another package.
> 
> Yeah, I'm also using another package it doesn't have models for each response but they at least provide the json response from dialog flow so you work from there.

Hi, May I know what is the package you are using on?

**Comment by bashiryousufy** [comment]
> @bashiryousufy @Makdan1 Can you guys suggest another package with null aware working with latest update of flutter? I have problem wtih welcome intent as well as suggestion chips from google assistance.

I'm using this package:
dialogflow_flutter: ^1.0.0
https://pub.dev/packages/dialogflow_flutter
