### ISSUE TITLE
[BUG ?]  detectIntent throws Exception

### ISSUE THREAD

**Issue by cto-leaps** [Deimos-Applications/dialog_flowtter#14]
**Describe the bug**
Using the code provided in the Example, whenever I try to use

```
    DetectIntentResponse response = await dialogFlowInstance.detectIntent(
      queryInput: queryInput,
    );
```
I get this;

```
Exception has occurred.
ArgumentError (Invalid argument(s): Invalid internet address accounts.google.com)
```

Forcing the execution to continue throws the same Exception again, then it seems to go through as I get a real response.

`flutter: DetectIntentResponse(a3b83791-23b1-411a-9156-c31726a8b27c-48f56f2f, QueryResult(how are  you?, en, null, smalltalk.greetings.how_are_you, {}, true, [Message(DialogPlatform.PLATFORM_UNSPECIFIED, DialogText([I'm doing very well. Thanks!]), null, null, null, null, null, null, null, null, null, null, null, null, null)], null, Intent(null, null, null, null, null, null, null, null, null, null, null, null, null, null), 1.0, null, null), null, null)`

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95
    darwin-arm, locale en-FR)
[!] Android toolchain - develop for Android devices (Android
    SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for
      more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK
      licenses.
      See
      https://flutter.dev/docs/get-started/install/macos#androi
      d-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.60.2)
[✓] Connected device (4 available)

I am not targeting Android for now.

Any idea what's going on here?

**Comment by ElZombieIsra** [comment]
Hi, did you copy and pasted the auth exactly as it is exported from DialogFlow? Sounds like you have an invalid url on your credentials.
Also it could be a internet permissions error.
