### ISSUE TITLE
[BUG] HandshakeException (HandshakeException: Connection terminated during handshake)

### ISSUE THREAD

**Issue by AlexandruFilipescu** [Deimos-Applications/dialog_flowtter#6]
**Describe the bug**
The app works fine for 1-2 minutes, but after running either my implementation or the one downloaded from the latest Github branch, it crashes...

Contry: Romania.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15964709/113520345-26e5dc80-959b-11eb-99ef-0caf83b6fa94.png)
![image](https://user-images.githubusercontent.com/15964709/113520385-60b6e300-959b-11eb-84e4-f00e7b50d548.png)
![image](https://user-images.githubusercontent.com/15964709/113520361-3bc27000-959b-11eb-8607-2ee336f94279.png)

**Smartphone (please complete the following information):**

- Pixel 2

**Package version**

- Version [e.g. 0.1.0]
0.3.0-nullsafety.0
And the latest version of the Github Branch....
**Stack Trace**
E/flutter (23676): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: HandshakeException: Connection terminated during handshake

**Flutter Doctor Info**
Add the `flutter doctor` command output

**Additional context**

**Comment by ElZombieIsra** [comment]
Hi, I just checked this and I'm not able to reproduce the error. Are you sure the device you're using has internet access?

Check that you have the internet permissions added to your `AndroidManifest.xml`.

Also, try to check with a physical device, that's always a better option. Let me know what you find out

**Comment by ElZombieIsra** [comment]
Also, I found [this answer](https://stackoverflow.com/questions/59561655/connection-terminated-during-handshake-flutter). Since you're in Romania, it can be related to that. Try to use a VPN and see if that helps

**Comment by AlexandruFilipescu** [comment]
I am using your exact same example just with the auth.JSON changed... Would you have time to try a share screen or something?

**Comment by ElZombieIsra** [comment]
Yeah, it must be a network-related issue. Try to use a VPN and let me know if you can connect with it

**Comment by AlexandruFilipescu** [comment]
With VPN(I tried 2, Avira and Windscribe) I get no response and still the same crash 
![image](https://user-images.githubusercontent.com/15964709/113669799-ef6f5100-96bc-11eb-96b6-b6e9bc16354c.png)

**Comment by AlexandruFilipescu** [comment]
I will try 2 things, put in a try catch the part that gives the error, and put the app on a real device....

**Comment by AlexandruFilipescu** [comment]
Update: On a real device works well with 0.2.0 version.
