### ISSUE TITLE
[FEATURE] Update http package dependency to version ^0.13.1

### ISSUE THREAD

**Issue by maxfer1221** [Deimos-Applications/dialog_flowtter#7]
It is difficult to manage conflicting dependencies between dialog_flowtter and other packages (namely firebase_auth) as they both utilize different http versions.

Updating the http package dependency version to ^0.13.1 would bring this package up to date with other contemporary packages and would resolve many conflicts.

I've attempted to solve these conflicting dependencies by simply downgrading my http version to no avail, so this seems like a simple enough solution that would facilitate access to all future users.

**Comment by ElZombieIsra** [comment]
Hey, that version of http has now migrated to using null-safety. I think for you to use it need to be using Flutter 2.0. Fortunately we have a null-safety version of this package. Update the dependency on your `pubspec.yaml` to use version 0.3.0 like this `dialog_flowtter: ^0.3.0-nullsafety.0`

I will check if I can upgrade it without null-safety support so I can publish a 0.2.x version

Let me know if that solved your problem so I can close this issue

**Comment by maxfer1221** [comment]
That solved my issue!
Thank you for the quick response and for the upkeep on this package! Very much appreciated.
