### ISSUE TITLE
Creating a message type to access in the library

### ISSUE THREAD

**Issue by SmiffyKMc** [Deimos-Applications/dialog_flowtter#9]
I see you have your message types, and can also see you have the card showing in the example. But when using Dialogflow to create responses, what does the library Message components expect to see to set its Message type? For instance, using the Default response, you are given two options, Text and Payload. Action on Google has many more options, but the library doesn't seem to work well with it, not being able to read its response type.

What Dialogflow response's should we use to allow for the library to extract the message type. Do you have an example?

**Comment by KieranMccarthyVersion1** [comment]
@ElZombieIsra Was wondering if you could assist here? Just what to create in the response on Dialogflow that will allow the library to render those cards, carousels etc?

**Comment by ElZombieIsra** [comment]
Hey guys.
So, [this line](https://github.com/Deimos-Applications/dialog_flowtter/blob/master/lib/src/models/intent/message.dart#L88) it's what's determines the Message type for the intent. 
We're checking several props that the API from DialogFlow sends to the library.
As for the Card, check the example code in [this line](https://github.com/Deimos-Applications/dialog_flowtter/blob/master/example/lib/app_body.dart#L58) and [this widget](https://github.com/Deimos-Applications/dialog_flowtter/blob/master/example/lib/app_body.dart#L83)

What I'm doing in the DialogFlow console inside the intent is adding a custom response pressing this icon

![Captura de pantalla 2021-04-23 a las 8 09 51 p m](https://user-images.githubusercontent.com/17725111/115942524-4ec8b180-a470-11eb-9c96-6cb7b70fe0b5.png)

Then pressing "Facebook"

![Captura de pantalla 2021-04-23 a las 8 10 19 p m](https://user-images.githubusercontent.com/17725111/115942549-63a54500-a470-11eb-9739-df01b6b028dc.png)

Then inside the "Facebook" tab, pressing "Add Responses"

![Captura de pantalla 2021-04-23 a las 8 11 00 p m](https://user-images.githubusercontent.com/17725111/115942577-8899b800-a470-11eb-98ec-520813d2912a.png)

After that, you select "Card"

![Captura de pantalla 2021-04-23 a las 8 11 39 p m](https://user-images.githubusercontent.com/17725111/115942589-98b19780-a470-11eb-8404-7f8e939b7684.png)

And fill the inputs as you wish

![Captura de pantalla 2021-04-23 a las 8 15 41 p m](https://user-images.githubusercontent.com/17725111/115942616-b41ca280-a470-11eb-8c97-cc5a11b9a3a9.png)

Hope that helps. Let me know if we can close this issue and if you need anything else

**Comment by SmiffyKMc** [comment]
That's very helpful! We originally tried Google Assistant as there were more responses to return. Was there a reason why ye didn't look at Google Assistant for response types?

**Comment by SmiffyKMc** [comment]
Nevermind, thanks for your help, it's working as expected :)

**Comment by bashiryousufy** [comment]
Can you also give us a demo for suggestion chip from google assistance?

**Comment by reconftw010101** [comment]
@bashiryousufy  Have you figure out for google assistance ??
